# 关于Osu!游戏
osu:
  # 管理osu!到MC的空间重映射
  screen:
    # 玩家应该有多大的屏幕横向距离？（单位：块）过大的屏幕可能导致玩家够不到。
    horizon-size: 4.0
    # 玩家应该有多大的屏幕垂直距离？（单位：块）过大的屏幕可能导致玩家够不到。
    vertical-size: 2.5
  # 管理每个击打物件
  hit-object:
    # 每个物件每tick应该移动多长距离？
    speed: 0.2
    # 每个物件应该在多远的位置生成实体？（单位：块）过大的距离可能导致意外的错误。
    view-distance: 32.0
    # 玩家应该从多长的距离开始击打物件？
    hit-distance: 0.5
